---
version: 2.1

executors:
  python3:
    docker:
      - image: circleci/python:3.8

jobs:
  full-make:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - checkout
      - run: make installdeps
      - run: make clean
      - run: make
      - store_artifacts:
          path: main.pdf
          destination: main.pdf

workflows:
  push:
    jobs:
      - full-make:
          exec: python3
